name: adaptify
description: A library for adaptive decision-making with Dart.
version: 1.0.0
author: Daniel Bälz <me@dbaelz.de>
homepage: https://github.com/dbaelz/adaptify

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  fuzzylogic: "^0.1.4"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
